# -*- coding: utf-8 -*-
"""retospotify

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aDX8NNsckx5WSfG_mKLOu2eJ3qanoT3_

**Libreria**
"""

import json
import pandas as pd
import numpy as np

"""**Leer el archivo json**

"""

#codigo para leer el archivo json
data = "taylor_swift_spotify.json"
Dataframe1 = pd.read_json(data, orient="records")
print(Dataframe1)

"""**Leer el archivo csv**"""

#codigo para leer el archivo csv
Dataframe1 = pd.read_csv("dataset.csv")
print(Dataframe1)

"""**convertir json a dataset**"""

with open('taylor_swift_spotify.json') as json_file:
    data = json.load(json_file)

df = pd.json_normalize(data)


df.to_csv('datos.csv', index=False)

df_csv = pd.read_csv('datos.csv')
print(df_csv)

"""**Reporte obtenido**"""

df = pd.read_csv('datos.csv')


info_general = df.info()


estadisticas_descriptivas = df.describe()

valores_nulos = df.isnull().sum()

duplicados = df[df.duplicated()]


tipos_de_datos = df.dtypes


anomalias_numericas = df.select_dtypes(include=[np.number]).apply(lambda x: x.isnull().sum())
anomalias_categoricas = df.select_dtypes(include=[np.object]).apply(lambda x: x.isnull().sum())


with open('reporte_calidad_datos.txt', 'w') as f:
    f.write("Información General:\n")
    f.write(str(info_general) + '\n\n')

    f.write("Estadísticas Descriptivas:\n")
    f.write(str(estadisticas_descriptivas) + '\n\n')

    f.write("Valores Nulos por Columna:\n")
    f.write(str(valores_nulos) + '\n\n')

    f.write("Duplicados en el Dataset:\n")
    f.write(str(duplicados) + '\n\n')

    f.write("Tipos de Datos por Columna:\n")
    f.write(str(tipos_de_datos) + '\n\n')

    f.write("Anomalías Numéricas:\n")
    f.write(str(anomalias_numericas) + '\n\n')

    f.write("Anomalías Categóricas:\n")
    f.write(str(anomalias_categoricas) + '\n\n')


print("Análisis de calidad de datos completado. Resultados guardados en 'reporte_calidad_datos.txt'.")